name: Deploy to AWS

on:
  push:
    branches:
      - main
      - test-workpress
  paths:
    - ".github/workflows/deploy_wordpress.yml"
    - "modules/**"
    - "**.tf"
    - "**.tfvars"
    - "deploy.sh"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_RDS_USER_NAME:  ${{ vars.TF_VAR_RDS_USER_NAME }}
          TF_VAR_RDS_PASSWORD:  ${{ secrets.TF_VAR_RDS_PASSWORD }}
          TF_VAR_DB_NAME:  ${{ vars.TF_VAR_DB_NAME }}
          TF_VAR_KEY_PAIR_NAME:  ${{ secrets.TF_VAR_KEY_PAIR_NAME }}
          TF_VAR_REDIS_CLUSTER_ID:  ${{ vars.TF_VAR_REDIS_CLUSTER_ID }}

      - name: Get Terraform Outputs
        id: tf_outputs
        run: |
          echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
          echo "RDS_ENDPOINT=$(terraform output -raw rds_endpoint)" >> $GITHUB_ENV
          echo "REDIS_ENDPOINT=$(terraform output -raw redis_endpoint)" >> $GITHUB_ENV

      - name: Save Private Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > word-press-key.pem
          chmod 400 "word-press-key.pem"

      - name: Deploy to EC2
        run: |
          chmod +x deploy.sh
          ./deploy.sh
        env:
          TF_VAR_RDS_USER_NAME: ${{ vars.TF_VAR_RDS_USER_NAME }}
          TF_VAR_RDS_PASSWORD: ${{ secrets.TF_VAR_RDS_PASSWORD }}
          TF_VAR_DB_NAME: ${{ vars.TF_VAR_DB_NAME }}
          TF_VAR_KEY_PAIR_NAME: ${{ secrets.TF_VAR_KEY_PAIR_NAME }}
          TF_VAR_REDIS_CLUSTER_ID: ${{ vars.TF_VAR_REDIS_CLUSTER_ID }}
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          AWS_REGION: ${{ vars.AWS_REGION }}
